name: LLVM-sh

on:
  push:
    branches:
      - main

jobs:
  llvm_13-ubuntu_20_04:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: llvm-13
        run: sudo ./llvm.sh 13

  llvm_12-ubuntu_20_04:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: llvm-12
        run: sudo ./llvm.sh 12

  llvm_13-ubuntu_18_04:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: llvm-13
        run: sudo ./llvm.sh 13

  llvm_12-ubuntu_18_04:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: llvm-12
        run: sudo ./llvm.sh 12

